# render.yaml
services:
  - type: web
    name: lucid-md
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: RATE_LIMIT
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 3600000
